apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: stuart
  name: stuart
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stuart
  strategy: {}
  template:
    metadata:
      labels:
        app: stuart
    spec:
      containers:
      - image: 
        name: stuart
        ports:
        - containerPort: 8000
        resources: {}
status: {}
