apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: stuart
  name: stuart
  namespace: stuart
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stuart
  strategy: {}
  template:
    metadata:
      labels:
        app: stuart
    spec:
      containers:
      - image: $DOCKER_IMAGE
        name: stuart
        ports:
        - containerPort: 8000
        resources:
          requests:
            memory: "50Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"        