apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: stuart
  name: stuart
  namespace: stuart
spec:
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: stuart
  type: LoadBalancer
status:
  loadBalancer: {}
